### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by fergusean** [packetbeat/packetbeat#101]
I've got Packetbeat running on an app server that sees a LOT of traffic.  It's crashing after just an hour or so of use.  I'm betting it has something to do with the size of the MySQL result set being returned from the DB.  Is there any way to configure it to use more memory and/or to discard MySQL results larger than a certain size?

I unfortunately can't share a pcap, as the data is confidential, but here's the backtrace:

```
fatal error: runtime: out of memory

goroutine 16 [running]:
runtime.throw(0xcf65f7)
        /usr/local/go/src/pkg/runtime/panic.c:520 +0x69 fp=0xc20811f1b0 sp=0xc20811f198
runtime.SysMap(0xc3a81a0000, 0x72ec0000, 0x1250e00, 0x1240e18)
        /usr/local/go/src/pkg/runtime/mem_linux.c:147 +0x93 fp=0xc20811f1e0 sp=0xc20811f1b0
runtime.MHeap_SysAlloc(0x124ce00, 0x72ec0000)
        /usr/local/go/src/pkg/runtime/malloc.goc:616 +0x15b fp=0xc20811f238 sp=0xc20811f1e0
MHeap_Grow(0x124ce00, 0x39760)
        /usr/local/go/src/pkg/runtime/mheap.c:319 +0x5d fp=0xc20811f278 sp=0xc20811f238
MHeap_AllocLocked(0x124ce00, 0x39755, 0x0)
        /usr/local/go/src/pkg/runtime/mheap.c:222 +0x379 fp=0xc20811f2b8 sp=0xc20811f278
runtime.MHeap_Alloc(0x124ce00, 0x39755, 0x10100000000)
        /usr/local/go/src/pkg/runtime/mheap.c:178 +0x7b fp=0xc20811f2e0 sp=0xc20811f2b8
largealloc(0x0, 0xc20811f390)
        /usr/local/go/src/pkg/runtime/malloc.goc:224 +0xa2 fp=0xc20811f328 sp=0xc20811f2e0
runtime.mallocgc(0x72eaa000, 0x721f81, 0x0)
        /usr/local/go/src/pkg/runtime/malloc.goc:169 +0xb6 fp=0xc20811f390 sp=0xc20811f328
growslice1(0x70dba0, 0xc34c2a0000, 0x5beee00, 0x5beee00, 0x5beee01, 0xc20811f450)
        /usr/local/go/src/pkg/runtime/slice.goc:125 +0x107 fp=0xc20811f3e0 sp=0xc20811f390
runtime.growslice(0x70dba0, 0xc34c2a0000, 0x5beee00, 0x5beee00, 0x1, 0x0, 0x0, 0x0)
        /usr/local/go/src/pkg/runtime/slice.goc:76 +0xbb fp=0xc20811f428 sp=0xc20811f3e0
main.parseMysqlResponse(0xc20946a000, 0x1190c, 0x12000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/vagrant/src/packetbeat/mysql.go:611 +0x5e3 fp=0xc20811f650 sp=0xc20811f428
main.receivedMysqlResponse(0xc20a49e600)
        /home/vagrant/src/packetbeat/mysql.go:465 +0x708 fp=0xc20811f7b8 sp=0xc20811f650
main.func·001(0xc20a49e600, 0xc209999e80, 0x1901, 0xc20946a000, 0x1190c, 0x12000)
        /home/vagrant/src/packetbeat/mysql.go:372 +0x111 fp=0xc20811f8a0 sp=0xc20811f7b8
main.ParseMysql(0xc209ac6c00, 0xc209999e80, 0xc2094b4801)
        /home/vagrant/src/packetbeat/mysql.go:349 +0x3ae fp=0xc20811f978 sp=0xc20811f8a0
main.(*TcpStream).AddPacket(0xc209999e80, 0xc209ac6c00, 0xc2090a5040, 0x1)
        /home/vagrant/src/packetbeat/tcp.go:105 +0x15c fp=0xc20811f9a8 sp=0xc20811f978
main.FollowTcp(0xc2090a5040, 0xc209ac6c00)
        /home/vagrant/src/packetbeat/tcp.go:209 +0x7d9 fp=0xc20811faf8 sp=0xc20811f9a8
main.(*DecoderStruct).DecodePacketData(0xc2090a4d80, 0xc20b73a000, 0x1950, 0x1950, 0xc20b4c33b0)
        /home/vagrant/src/packetbeat/tcp.go:362 +0x3c5 fp=0xc20811fbb8 sp=0xc20811faf8
main.main()
        /home/vagrant/src/packetbeat/main.go:351 +0x1f7a fp=0xc20811ff50 sp=0xc20811fbb8
runtime.main()
        /usr/local/go/src/pkg/runtime/proc.c:247 +0x11a fp=0xc20811ffa8 sp=0xc20811ff50
runtime.goexit()  
        /usr/local/go/src/pkg/runtime/proc.c:1445 fp=0xc20811ffb0 sp=0xc20811ffa8
created by _rt0_go
        /usr/local/go/src/pkg/runtime/asm_amd64.s:97 +0x120

goroutine 19 [finalizer wait]:
runtime.park(0x452040, 0xd0f090, 0xcf9f89)
        /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xd0f090, 0xcf9f89)
        /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()  
        /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall, 309 minutes]:
os/signal.loop()  
        /usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 17 [syscall, 309 minutes]:
runtime.goexit()  
        /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 22 [select]:
main.(*RedisOutputType).SendMessagesGoroutine(0xd11600)
        /home/vagrant/src/packetbeat/output_redis.go:182 +0x6ec
created by main.(*RedisOutputType).Init
        /home/vagrant/src/packetbeat/output_redis.go:122 +0x8e9

goroutine 23 [chan receive]:
main.(*PublisherType).UpdateTopologyPeriodically(0xd112c0)
        /home/vagrant/src/packetbeat/publish.go:228 +0x63
created by main.(*PublisherType).Init
        /home/vagrant/src/packetbeat/publish.go:368 +0xb05

goroutine 24 [chan receive]:
main.(*Process).RefreshPids(0xc20801af50)
        /home/vagrant/src/packetbeat/procs.go:139 +0xb9
created by main.NewProcess
        /home/vagrant/src/packetbeat/procs.go:132 +0x9d

goroutine 25 [chan receive]:
main.(*Process).RefreshPids(0xc20801afa0)
        /home/vagrant/src/packetbeat/procs.go:139 +0xb9
created by main.NewProcess
        /home/vagrant/src/packetbeat/procs.go:132 +0x9d

goroutine 26 [chan receive]:
main.(*Process).RefreshPids(0xc20801aff0)
        /home/vagrant/src/packetbeat/procs.go:139 +0xb9
created by main.NewProcess
        /home/vagrant/src/packetbeat/procs.go:132 +0x9d

goroutine 27 [chan receive]:
main.(*Process).RefreshPids(0xc20801b040)
        /home/vagrant/src/packetbeat/procs.go:139 +0xb9
created by main.NewProcess
        /home/vagrant/src/packetbeat/procs.go:132 +0x9d

goroutine 28 [chan receive, 309 minutes]:
main.(*Thrift).publishTransactions(0xd11060)
        /home/vagrant/src/packetbeat/thrift.go:983 +0x5f
created by main.(*Thrift).Init
        /home/vagrant/src/packetbeat/thrift.go:246 +0xe3

goroutine 29 [chan receive, 309 minutes]:
main.func·004()   
        /home/vagrant/src/packetbeat/main.go:278 +0x44
created by main.main
        /home/vagrant/src/packetbeat/main.go:281 +0x14e6
```

**Comment by tsg** [comment]
Based on the stacktrace, it could also be a bug in the parsing of the MySQL answer. We read the length of a particular string, and perhaps that is extremely large, so the following memory allocation fails.

If you want, we can have a look together at this sometimes next week, via chat or google hangouts. I could prepare a special debug build to help with troubleshooting. Send me an email at tudor@packetbeat.com if you are available.

**Comment by tsg** [comment]
Status update on this one: the issue is caused by the mysql row parser taking potentially unlimited memory when parsing arbitrarily large responses. A test build that limits the number of rows parsed seems to do well. Commits to follow.
