### ISSUE TITLE
[CentOS 6.6 - EC2 - 0.4.3] panic: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by adinapoli** [packetbeat/packetbeat#89]
Hello,

I have installed packetbeat on my CentOS Amazon EC2 machine following the getting started guide.
After installing the latest packetbeat, the agent crash with `panic: runtime error: slice bounds out of range`:

```
rpm -vi packetbeat-0.4.3-1.el6.x86_64.rpm
packetbeat -e -c /etc/packetbeat/packetbeat.conf -d "ip,ipdetailed"

output_elasticsearch.go:55: INFO [ElasticsearchOutput] Using Elasticsearch http://localhost:9200
output_elasticsearch.go:56: INFO [ElasticsearchOutput] Using index pattern [packetbeat-]YYYY.MM.DD
output_elasticsearch.go:57: INFO [ElasticsearchOutput] Topology expires after 15s
publish.go:285: INFO Using Elasticsearch to store the topology
publish.go:345: INFO No agent name configured, using hostname 'ip-172-31-43-204.eu-west-1.compute.internal'
publish.go:358: INFO Topology map refreshed every 10s
panic: runtime error: slice bounds out of range

goroutine 16 [running]:
runtime.panic(0x7ead60, 0xcf5d0f)
        /usr/local/go/src/pkg/runtime/panic.c:279 +0xf5
github.com/nranchev/go-libGeoIP.Load(0x8d05d0, 0x1a, 0xc2090bdc80, 0x0, 0x0)
        /home/vagrant/src/github.com/nranchev/go-libGeoIP/libgeo.go:173 +0x507
main.loadGeoIPData()
        /home/vagrant/rpmbuild/BUILD/packetbeat/main.go:143 +0x1e6
main.main()
        /home/vagrant/rpmbuild/BUILD/packetbeat/main.go:247 +0xfae

goroutine 19 [finalizer wait]:
runtime.park(0x451b50, 0xd0d0b0, 0xcf7fa9)
        /usr/local/go/src/pkg/runtime/proc.c:1369 +0x89
runtime.parkunlock(0xd0d0b0, 0xcf7fa9)
        /usr/local/go/src/pkg/runtime/proc.c:1385 +0x3b
runfinq()
        /usr/local/go/src/pkg/runtime/mgc0.c:2644 +0xcf
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 20 [syscall]:
os/signal.loop()
        /usr/local/go/src/pkg/os/signal/signal_unix.go:21 +0x1e
created by os/signal.init·1
        /usr/local/go/src/pkg/os/signal/signal_unix.go:27 +0x32

goroutine 17 [syscall]:                                                                                                                      [21/1878]
runtime.goexit()
        /usr/local/go/src/pkg/runtime/proc.c:1445

goroutine 21 [chan receive]:
github.com/bitly/go-hostpool.(*epsilonGreedyHostPool).epsilonGreedyDecay(0xc208050880)
        /home/vagrant/src/github.com/bitly/go-hostpool/epsilon_greedy.go:78 +0x7a
created by github.com/bitly/go-hostpool.NewEpsilonGreedy
        /home/vagrant/src/github.com/bitly/go-hostpool/epsilon_greedy.go:64 +0x29b

goroutine 27 [runnable]:
main.(*PublisherType).UpdateTopologyPeriodically(0xd0f2e0)
        /home/vagrant/rpmbuild/BUILD/packetbeat/publish.go:227
created by main.(*PublisherType).Init
        /home/vagrant/rpmbuild/BUILD/packetbeat/publish.go:368 +0xb05

goroutine 25 [runnable]:
net/http.(*persistConn).readLoop(0xc208068160)
        /usr/local/go/src/pkg/net/http/transport.go:868 +0x829
created by net/http.(*Transport).dialConn
        /usr/local/go/src/pkg/net/http/transport.go:600 +0x93f

goroutine 26 [select]:
net/http.(*persistConn).writeLoop(0xc208068160)
        /usr/local/go/src/pkg/net/http/transport.go:885 +0x38f
created by net/http.(*Transport).dialConn
        /usr/local/go/src/pkg/net/http/transport.go:601 +0x957

goroutine 28 [runnable]:
main.(*Process).RefreshPids(0xc2090e26e0)
        /home/vagrant/rpmbuild/BUILD/packetbeat/procs.go:137
created by main.NewProcess
        /home/vagrant/rpmbuild/BUILD/packetbeat/procs.go:132 +0x9d

goroutine 29 [runnable]:
main.(*Process).RefreshPids(0xc2090e2730)
        /home/vagrant/rpmbuild/BUILD/packetbeat/procs.go:137
created by main.NewProcess
        /home/vagrant/rpmbuild/BUILD/packetbeat/procs.go:132 +0x9d

goroutine 30 [runnable]:
main.(*Process).RefreshPids(0xc2090e2780)
        /home/vagrant/rpmbuild/BUILD/packetbeat/procs.go:137
created by main.NewProcess
        /home/vagrant/rpmbuild/BUILD/packetbeat/procs.go:132 +0x9d

goroutine 31 [runnable]:
main.(*Process).RefreshPids(0xc2090e27d0)
        /home/vagrant/rpmbuild/BUILD/packetbeat/procs.go:137
created by main.NewProcess
        /home/vagrant/rpmbuild/BUILD/packetbeat/procs.go:132 +0x9d

goroutine 33 [runnable]:
main.(*Thrift).publishTransactions(0xd0f080)
        /home/vagrant/rpmbuild/BUILD/packetbeat/thrift.go:982
created by main.(*Thrift).Init
        /home/vagrant/rpmbuild/BUILD/packetbeat/thrift.go:246 +0xe3
```

Elasticsearch is installed and listening on port 9200.
Any idea?

Thanks!
Alfredo

**Comment by tsg** [comment]
The error seems to come from the libgeoip library. Which GeoIP package do you have installed? Also, let me know the CentOS version, please.

**Comment by adinapoli** [comment]
@tsg I do not have any actually, because the instruction didn't mention it, so any pointer in that direction would be appreciated. 
CentOS version is `Red Hat Enterprise Linux Server release 6.6 (Santiago)`

**Comment by adinapoli** [comment]
Addendum: I did

```
yum install geoip geoip-devel
```

But with no success. Any other step I might be missing? Thanks guys!

**Comment by tsg** [comment]
Thanks, right, there are some issues with handling the symlink. On CentOS, GeoIP.dat is a symlink to GeoLiteCountry.dat. Here is an alternative workaround until we fix this:

* Make sure you have `/usr/share/GeoIP/GeoLiteCountry.dat`. I got it with: `yum install geoip-geolite`.

* Add to the end of your `/etc/packetbeat/packetbeat.conf`:

     [geoip]
     paths = ["/usr/share/GeoIP/GeoLiteCountry.dat"]

Btw, @adinapoli I think you need the `GeoLiteCountry.dat` instead of `GeoLiteCity.dat` for the default dashboards to work.

**Comment by adinapoli** [comment]
Ah, thanks @tsg , is very useful!

I'm really enjoying packetbeat so far :)

A.
